import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Both sidebars are generated from the docs folder structure. Ordering and
// labels come from each subfolder's _category_.json and per-file frontmatter.
const sidebars: SidebarsConfig = {
  administratorManualSidebar: [
    {type: 'autogenerated', dirName: 'administrator-manual'},
  ],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],
};

export default sidebars;
